### ISSUE TITLE
brimcap load/analyze progressing to 1.0% and then hanging

### ISSUE THREAD

**Issue by philrz** [brimdata/brimcap#111]
Repro is with Brimcap commit 357bd57 and Zed commit `389b120`.

While attempting to verify the fix for #71, I stumbled into what looks like a new issue. To repro, I start a `zed lake serve` and then attempt to load this [wrccdc pcap](https://archive.wrccdc.org/pcaps/2018/wrccdc.2018-03-23.010014000000000.pcap.gz) (after uncompressing) via:

```
$ brimcap load -root ~/brimcap-root -p wrccdc.pcap ~/pcap/wrccdc.pcap
```

As shown in the attached video, the progress meter seems to proceed very slowly, and shortly after it gets to `1.0%`, the record/byte counts stop incrementing and it hangs indefinitely. I eventually kill it by hitting Ctrl-`\`, and the stack dump is pasted below after the video.

https://user-images.githubusercontent.com/5934157/124016321-605f9580-d99a-11eb-9b98-42450f1b0b01.mp4

```
$ brimcap load -root ~/brimcap-root -p wrccdc.pcap ~/pcap/wrccdc.pcap 
  1.0% 476MiB858KiB604B/476MiB858KiB604B records=670823 
^\SIGQUIT: quit
PC=0x7fff2046acde m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x2060220, 0x20601e0, 0x0)
	/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:384 +0x39
runtime.semasleep(0xffffffffffffffff, 0xc00004b000)
	/usr/local/opt/go/libexec/src/runtime/os_darwin.go:63 +0x8d
runtime.notesleep(0x205ffd0)
	/usr/local/opt/go/libexec/src/runtime/lock_sema.go:181 +0xdb
runtime.mPark()
	/usr/local/opt/go/libexec/src/runtime/proc.go:1340 +0x39
runtime.stoplockedm()
	/usr/local/opt/go/libexec/src/runtime/proc.go:2495 +0x6e
runtime.schedule()
	/usr/local/opt/go/libexec/src/runtime/proc.go:3103 +0x48c
runtime.park_m(0xc000001c80)
	/usr/local/opt/go/libexec/src/runtime/proc.go:3318 +0x9d
runtime.mcall(0x106ef36)
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:327 +0x5b

goroutine 1 [semacquire, 1 minutes]:
sync.runtime_Semacquire(0xc0002fc640)
	/usr/local/opt/go/libexec/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0002fc638)
	/usr/local/opt/go/libexec/src/sync/waitgroup.go:130 +0x65
golang.org/x/sync/errgroup.(*Group).Wait(0xc0002fc630, 0xc0002fc690, 0x1b98238)
	/Users/phil/.go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x31
github.com/brimdata/brimcap/cmd/brimcap/load.(*Command).Run(0xc0002e6000, 0xc0000320d0, 0x1, 0x1, 0x0, 0x0)
	/Users/phil/work/brimcap/cmd/brimcap/load/command.go:111 +0x6ea
github.com/brimdata/zed/pkg/charm.path.run(0xc0002c6410, 0x2, 0x2, 0xc0000320d0, 0x1, 0x1, 0xc0002c6410, 0x2)
	/Users/phil/.go/pkg/mod/github.com/brimdata/zed@v0.29.1-0.20210628182317-389b1200a929/pkg/charm/path.go:11 +0x8f
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0x20535e0, 0xc000032080, 0x6, 0x6, 0xffffffff, 0xc00009e058)
	/Users/phil/.go/pkg/mod/github.com/brimdata/zed@v0.29.1-0.20210628182317-389b1200a929/pkg/charm/charm.go:63 +0x1e7
main.main()
	/Users/phil/work/brimcap/cmd/brimcap/main.go:19 +0x74

goroutine 18 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/opt/go/libexec/src/runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	/usr/local/opt/go/libexec/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/opt/go/libexec/src/os/signal/signal.go:151 +0x45

goroutine 7 [select, 1 minutes]:
os/signal.NotifyContext.func1(0xc000093880)
	/usr/local/opt/go/libexec/src/os/signal/signal.go:288 +0x8f
created by os/signal.NotifyContext
	/usr/local/opt/go/libexec/src/os/signal/signal.go:287 +0x1cf

goroutine 19 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0xac6f258, 0x72, 0xffffffffffffffff)
	/usr/local/opt/go/libexec/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc0000cec98, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/opt/go/libexec/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000cec80, 0xc000128000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc0000cec80, 0xc000128000, 0x1000, 0x1000, 0x103bedc, 0xc00007cc38, 0x1068860)
	/usr/local/opt/go/libexec/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc000126000, 0xc000128000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc0002ea5a0, 0xc000128000, 0x1000, 0x1000, 0xc00009e960, 0xc00007cd40, 0x1006c55)
	/usr/local/opt/go/libexec/src/net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc000118120)
	/usr/local/opt/go/libexec/src/bufio/bufio.go:101 +0x108
bufio.(*Reader).Peek(0xc000118120, 0x1, 0x0, 0x1, 0x4, 0x1, 0x3)
	/usr/local/opt/go/libexec/src/bufio/bufio.go:139 +0x4f
net/http.(*persistConn).readLoop(0xc0002ea5a0)
	/usr/local/opt/go/libexec/src/net/http/transport.go:2083 +0x1a8
created by net/http.(*Transport).dialConn
	/usr/local/opt/go/libexec/src/net/http/transport.go:1743 +0xc77

goroutine 20 [select]:
io.(*pipe).Read(0xc000118360, 0xc0006d6000, 0x8000, 0x8000, 0xbc, 0x18a0140, 0x1fddb80)
	/usr/local/opt/go/libexec/src/io/pipe.go:57 +0xcb
io.(*PipeReader).Read(0xc000152108, 0xc0006d6000, 0x8000, 0x8000, 0xbc, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/io/pipe.go:134 +0x4c
io.copyBuffer(0xbe310f0, 0xc0002ae200, 0x1b88220, 0xc000152108, 0xc0006d6000, 0x8000, 0x8000, 0xc00007bc38, 0x100cd05, 0x18ee100)
	/usr/local/opt/go/libexec/src/io/io.go:423 +0x12c
io.Copy(...)
	/usr/local/opt/go/libexec/src/io/io.go:382
net/http.(*transferWriter).doBodyCopy(0xc0002c8000, 0xbe310f0, 0xc0002ae200, 0x1b88220, 0xc000152108, 0x12f61f2, 0xc000126000, 0xc000129000)
	/usr/local/opt/go/libexec/src/net/http/transfer.go:409 +0x6a
net/http.(*transferWriter).writeBody(0xc0002c8000, 0x1b885c0, 0xc000126010, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/net/http/transfer.go:356 +0x531
net/http.(*Request).write(0xc000148300, 0x1b85940, 0xc00012a000, 0x0, 0xc00037e030, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/net/http/request.go:697 +0x7c6
net/http.(*persistConn).writeLoop(0xc0002ea5a0)
	/usr/local/opt/go/libexec/src/net/http/transport.go:2385 +0x1a7
created by net/http.(*Transport).dialConn
	/usr/local/opt/go/libexec/src/net/http/transport.go:1744 +0xc9c

goroutine 50 [select, 1 minutes]:
net/http.(*persistConn).roundTrip(0xc0002ea5a0, 0xc0006c6000, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/net/http/transport.go:2610 +0x765
net/http.(*Transport).roundTrip(0xc0000c9b80, 0xc000148200, 0xc0000f4420, 0x160, 0x150)
	/usr/local/opt/go/libexec/src/net/http/transport.go:592 +0xacb
net/http.(*Transport).RoundTrip(0xc0000c9b80, 0xc000148200, 0xc0000c9b80, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/net/http/roundtrip.go:17 +0x35
net/http.send(0xc000148200, 0x1b88420, 0xc0000c9b80, 0x0, 0x0, 0x0, 0xc000152120, 0xf8, 0x1, 0x0)
	/usr/local/opt/go/libexec/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0xc0002b9590, 0xc000148200, 0x0, 0x0, 0x0, 0xc000152120, 0x0, 0x1, 0xc000122247)
	/usr/local/opt/go/libexec/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0xc0002b9590, 0xc000148200, 0x0, 0x0, 0x0)
	/usr/local/opt/go/libexec/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
	/usr/local/opt/go/libexec/src/net/http/client.go:585
github.com/go-resty/resty/v2.(*Client).execute(0xc0002e8000, 0xc0000f4000, 0x0, 0x0, 0x0)
	/Users/phil/.go/pkg/mod/github.com/go-resty/resty/v2@v2.2.0/client.go:791 +0x2e7
github.com/go-resty/resty/v2.(*Request).Execute(0xc0000f4000, 0x19e657b, 0x4, 0xc00003c1e0, 0x25, 0x0, 0x0, 0x0)
	/Users/phil/.go/pkg/mod/github.com/go-resty/resty/v2@v2.2.0/request.go:622 +0x139
github.com/go-resty/resty/v2.(*Request).Send(...)
	/Users/phil/.go/pkg/mod/github.com/go-resty/resty/v2@v2.2.0/request.go:597
github.com/brimdata/zed/api/client.(*Connection).stream(0xc00000e630, 0xc0000f4000, 0x0, 0x0, 0x0)
	/Users/phil/.go/pkg/mod/github.com/brimdata/zed@v0.29.1-0.20210628182317-389b1200a929/api/client/connection.go:108 +0x96
github.com/brimdata/zed/api/client.(*Connection).Add(0xc00000e630, 0x1b98238, 0xc00012a0c0, 0x363296e1d36f6a0d, 0xfc75938e76a9ad35, 0x11126758, 0x1b88220, 0xc000152108, 0x0, 0x0, ...)
	/Users/phil/.go/pkg/mod/github.com/brimdata/zed@v0.29.1-0.20210628182317-389b1200a929/api/client/connection.go:357 +0x21f
github.com/brimdata/brimcap/cmd/brimcap/load.(*Command).post(0xc0002e6000, 0x1b98238, 0xc00012a0c0, 0xc000152108, 0x0, 0x0)
	/Users/phil/work/brimcap/cmd/brimcap/load/command.go:119 +0xb2
github.com/brimdata/brimcap/cmd/brimcap/load.(*Command).Run.func3(0x0, 0x0)
	/Users/phil/work/brimcap/cmd/brimcap/load/command.go:109 +0x45
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0002fc630, 0xc0002fc690)
	/Users/phil/.go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/phil/.go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66

rax    0x104
rbx    0x11fe7e00
rcx    0x7ffeefbff488
rdx    0x400
rdi    0x2060220
rsi    0x60100000700
rbp    0x7ffeefbff530
rsp    0x7ffeefbff488
r8     0x0
r9     0xa0
r10    0x0
r11    0x246
r12    0x20601e0
r13    0x16
r14    0x60100000700
r15    0x400
rip    0x7fff2046acde
rflags 0x247
cs     0x7
fs     0x0
gs     0x0
```

This was not happening as of Brimcap commit 6406f89 that came right before. In that case the progress bar incremented to `100.0%` and exited, with the byte counts at that point looking approximately the same as when the meter for the newer Brimcap was capped out at `1.0%`.

https://user-images.githubusercontent.com/5934157/124016863-ec71bd00-d99a-11eb-85f2-eabfa12de4d3.mp4

**Comment by philrz** [comment]
I also happened to find `brimcap analyze` exhibits the same symptom. I happened to be testing with Brimcap commit 79f8e17 at the time.

```
$ brimcap -version
Version: v0.0.5-20-g79f8e17

$ brimcap analyze -o out.zng wrccdc.pcap 
  1.0% 476MiB858KiB604B/476MiB858KiB604B records=670823 
^\SIGQUIT: quit
PC=0x7fff2046acde m=0 sigcode=0

goroutine 0 [idle]:
runtime.pthread_cond_wait(0x2060220, 0x20601e0, 0x0)
	/usr/local/opt/go/libexec/src/runtime/sys_darwin.go:384 +0x39
runtime.semasleep(0xffffffffffffffff, 0xc000048800)
	/usr/local/opt/go/libexec/src/runtime/os_darwin.go:63 +0x8d
runtime.notesleep(0x205ffd0)
	/usr/local/opt/go/libexec/src/runtime/lock_sema.go:181 +0xdb
runtime.mPark()
	/usr/local/opt/go/libexec/src/runtime/proc.go:1340 +0x39
runtime.stoplockedm()
	/usr/local/opt/go/libexec/src/runtime/proc.go:2495 +0x6e
runtime.schedule()
	/usr/local/opt/go/libexec/src/runtime/proc.go:3103 +0x48c
runtime.park_m(0xc000102a80)
	/usr/local/opt/go/libexec/src/runtime/proc.go:3318 +0x9d
runtime.mcall(0x106ef36)
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:327 +0x5b

goroutine 1 [chan send (nil chan)]:
github.com/gosuri/uilive.(*Writer).Stop(...)
	/Users/phil/.go/pkg/mod/github.com/gosuri/uilive@v0.0.4/writer.go:119
github.com/brimdata/brimcap/cli/analyzecli.(*statusLineDisplay).End(0xc0000a8480)
	/Users/phil/work/brimcap/cli/analyzecli/display.go:75 +0x66
github.com/brimdata/brimcap/cmd/brimcap/analyze.(*Command).Run(0xc0002c0100, 0xc000132040, 0x1, 0x1, 0x0, 0x0)
	/Users/phil/work/brimcap/cmd/brimcap/analyze/command.go:88 +0x494
github.com/brimdata/zed/pkg/charm.path.run(0xc0002d6440, 0x2, 0x2, 0xc000132040, 0x1, 0x1, 0xc0002d6440, 0x2)
	/Users/phil/.go/pkg/mod/github.com/brimdata/zed@v0.29.1-0.20210701211951-19d600933288/pkg/charm/path.go:11 +0x8f
github.com/brimdata/zed/pkg/charm.(*Spec).ExecRoot(0x20535e0, 0xc000132010, 0x4, 0x4, 0xffffffff, 0xc00010e058)
	/Users/phil/.go/pkg/mod/github.com/brimdata/zed@v0.29.1-0.20210701211951-19d600933288/pkg/charm/charm.go:63 +0x1e7
main.main()
	/Users/phil/work/brimcap/cmd/brimcap/main.go:19 +0x74

goroutine 34 [syscall, 2 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/opt/go/libexec/src/runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	/usr/local/opt/go/libexec/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/opt/go/libexec/src/os/signal/signal.go:151 +0x45

goroutine 5 [select, 2 minutes]:
os/signal.NotifyContext.func1(0xc00014db00)
	/usr/local/opt/go/libexec/src/os/signal/signal.go:288 +0x8f
created by os/signal.NotifyContext
	/usr/local/opt/go/libexec/src/os/signal/signal.go:287 +0x1cf

rax    0x104
rbx    0xaa06e00
rcx    0x7ffeefbff4b8
rdx    0x300
rdi    0x2060220
rsi    0x50100000600
rbp    0x7ffeefbff560
rsp    0x7ffeefbff4b8
r8     0x0
r9     0xa0
r10    0x0
r11    0x246
r12    0x20601e0
r13    0x16
r14    0x50100000600
r15    0x300
rip    0x7fff2046acde
rflags 0x247
cs     0x7
fs     0x0
gs     0x0
```

**Comment by mattnibs** [comment]
This appears to be fixed with https://github.com/brimdata/brimcap/pull/115

**Comment by philrz** [comment]
As shown in the attached video, I've verified in Brimcap 1760eba that this seems to be fixed for `brimcap analyze`, but the problem remains for `brimcap load`.

https://user-images.githubusercontent.com/5934157/124784121-7ae5c180-defa-11eb-941a-6de9650b57ab.mp4

Between https://github.com/brimdata/brim/issues/1716 and https://github.com/brimdata/brimcap/issues/113, the plan of record is to phase out `brimcap load` entirely, so it's assumed we can ignore that breakage.

Thanks @mattnibs!
